version: "3.7"
services:
  jenkins:
    container_name: sh_jenkins
    image: shahjalalh/jenkins:0.3
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8099:8080"
    volumes: 
      - "./jenkins_home:/var/jenkins_home"
      # - "/project/location:/home/workspace/project_env_name/project_name"
    networks:
      - net
networks:
  net:
