version: "3.7"
services:
  jenkins:
    container_name: sh_jenkins
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8099:8080"
    volumes: 
      - "./jenkins_home:/var/jenkins_home"
    networks:
      - net
networks:
  net:
